# Generated by Django 4.1.6 on 2023-02-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='<small class="text-muted">это наш заголовок категории товара</small><hr><br>', max_length=250, verbose_name='Заголовок категории товара')),
            ],
            options={
                'verbose_name': 'Категории историй',
                'verbose_name_plural': 'Категории историй',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='заголовок', help_text='<small class="text-muted">это наш заголовок</small><hr><br>', max_length=300, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, default='products/noprod.jpg', help_text='<small class="text-muted">это наш заставка</small><hr><br>', upload_to='products/', verbose_name='Заставка:')),
                ('price', models.IntegerField(blank=True, default='0', help_text='<small class="text-muted">Цена</small><hr><br>', null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, default='Описание', verbose_name='Описание')),
                ('productCategory', models.ManyToManyField(blank=True, default=None, help_text='<small class="text-muted">Категория товара</small><hr><br>', to='django_app.productcategory', verbose_name='Категория товара')),
            ],
        ),
    ]
