# Generated by Django 4.1.6 on 2023-03-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pproduct',
        ),
        migrations.AddField(
            model_name='order',
            name='pproduct',
            field=models.ManyToManyField(blank=True, default=None, help_text='<small class="text-muted">товары заказанные</small><hr><br>', to='django_app.product', verbose_name='товары'),
        ),
    ]
