# Generated by Django 4.1.6 on 2023-03-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_alter_order_author_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], max_length=20),
        ),
    ]
