# Generated by Django 4.1.6 on 2023-03-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.TextField(blank=True),
        ),
    ]
