# Generated by Django 4.1.6 on 2023-03-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_alter_order_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='<small class="text-muted">Статусы заказа</small><hr><br>', max_length=250, verbose_name='Статусы заказа')),
            ],
            options={
                'verbose_name': 'Статусы заказа',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.orderstatus', verbose_name='Статус заказа'),
        ),
    ]
