# Generated by Django 4.1.6 on 2023-03-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0013_deliverymethod_paymentmethod_remove_order_is_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pproduct',
        ),
    ]
