# Generated by Django 4.1.6 on 2023-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0014_remove_order_pproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.IntegerField(blank=True, help_text='<small class="text-muted">Цена</small><hr><br>', null=True, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.BooleanField(default=True, help_text='<small class="text-muted">наличие товара</small><hr><br>', verbose_name='Есть в наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_contact',
            field=models.CharField(blank=True, help_text='<small class="text-muted">Контакты склада</small><hr><br>', max_length=500, verbose_name='Контакты продовца'),
        ),
    ]
